version: "3.8"
services:
  app:
    build: .
    container_name: unk029_bank_app
    expose:
      - "8001"
    environment:
      TNS_ADMIN: /opt/oracle/wallet
    volumes:
      - ./wallet:/opt/oracle/wallet:ro
    env_file:
      - .env
  nginx:
    image: nginx:alpine
    container_name: unk029_nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./env/fullchain.pem:/etc/nginx/env/fullchain.pem:ro
      - ./env/privkey.pem:/etc/nginx/env/privkey.pem:ro
     
    depends_on:
      - app